# This is a Docker Compose file for a group to-do application
# It sets up a frontend using Nginx, a backend service, and a MySQL database.
services:
  frontend: 
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "8080:80"
    networks:
      - group-to-do-app

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "3050:3050"
    networks:
      - group-to-do-app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - group-to-do-app
    command: --default-authentication-plugin=mysql_native_password --skip-name-resolve
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  group-to-do-app:
    driver: bridge

volumes:
  db-data:
